name: collection_providers
description: A group of pre-built providers the wrap the basic dart collections
  - list, set, map
version: 0.1.0
homepage: https://flutter.institute/
repository: https://github.com/flutter-institute/collection_providers
issue_tracker: https://github.com/flutter-institute/collection_providers/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0 # Static analysis rules
